from flask import Flask, jsonify
from stock_data import get_stock_data
from flask_cors import CORS  # Import CORS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

app = Flask(__name__)
CORS(app)  # Enable CORS on the Flask app

# comunication route to show selected set of array's specifyed in index.js 
@app.route('/api/stock/<symbol>')
def stock(symbol):
    data = get_stock_data(symbol)
    return jsonify(data)

if __name__ == '__main__':
    app.run(debug=True)
